# Generated by Django 2.2.18 on 2021-03-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
