# Generated by Django 2.2.18 on 2021-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='segundo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
