# Generated by Django 2.2.18 on 2021-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sc_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(help_text='Ingrese el nombre del autor del articulo', max_length=200)),
                ('doi', models.CharField(max_length=30, verbose_name='DOI')),
            ],
        ),
    ]
