# Generated by Django 2.2.18 on 2021-03-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210312_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_article',
            name='palabras',
            field=models.ManyToManyField(to='catalog.Claves'),
        ),
        migrations.AlterField(
            model_name='sc_article',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor'),
        ),
    ]
