# Generated by Django 2.2.18 on 2021-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210312_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sc_Article',
            new_name='Articles',
        ),
    ]
